name: 'Test'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-action:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test replace-comment action
        uses: ./
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: '<!-- test-comment -->'
          comment-author: 'github-actions[bot]'
          body: |
            <!-- test-comment -->
            ## 🧪 Test Comment
            This comment was created by the replace-comment action!
            **PR:** #${{ github.event.pull_request.number }}
            **Commit:** ${{ github.sha }}
            **Run:** [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            **Time:** $(date -u)
          reactions: 'rocket,eyes'
